### ISSUE TITLE
Ability Books Should have Appropriate Tint

### ISSUE THREAD

**Issue by Gogo1951** [ahakola/AlreadyKnown#1]
It's tinting by class, but not by level. On a 57 hunter, the books show up as usable but they are not until 60.

![image](https://user-images.githubusercontent.com/55365231/93169515-dab07900-f6ea-11ea-923f-4ac8c3df15db.png)

**Comment by ahakola** [comment]
Pushed new version of the AlreadyKnown.lua to the repository that should be able to detect items that are above your level. Please note the addon only tints items in MerchantFrame, AuctionHouseUI and GuildBankUI (not present in Classic)

**Comment by ahakola** [comment]
> Let me know if this causes any errors for you.

Closing this as I haven't heard anything for almost four years now.
