### ISSUE TITLE
Issue when visiting the Auction House

### ISSUE THREAD

**Issue by tgi-filip** [ahakola/AlreadyKnown#10]
Message: Interface/AddOns/AlreadyKnown/AlreadyKnown.lua:443: hooksecurefunc(): OnScrollBoxRangeChanged is not a function
Time: Wed Jan 17 19:29:03 2024
Count: 1
Stack: Interface/AddOns/AlreadyKnown/AlreadyKnown.lua:443: hooksecurefunc(): OnScrollBoxRangeChanged is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@Interface/AddOns/AlreadyKnown/AlreadyKnown.lua"]:443: in function <Interface/AddOns/AlreadyKnown/AlreadyKnown.lua:438>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:576: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:615: in function `AuctionHouseFrame_LoadUI'
[string "@Interface/FrameXML/UIParent.lua"]:2082: in function <Interface/FrameXML/UIParent.lua:1441>
[string "=[C]"]: ?

Locals:

**Comment by Taizunz** [comment]
Getting the same error, but with TSM mentioned in the error. Happens immediately after logging in.

```
3x AlreadyKnown/AlreadyKnown.lua:443: hooksecurefunc(): OnScrollBoxRangeChanged is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@AlreadyKnown/AlreadyKnown.lua"]:443: in function <AlreadyKnown/AlreadyKnown.lua:438>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@TradeSkillMaster/Core/UI/AuctionUI/Core.lua"]:50: in function `_callback'
[string "@TradeSkillMaster/LibTSM/Util/Delay.lua"]:100: in function <TradeSkillMaster/LibTSM/Util/Delay.lua:93>
[string "@TradeSkillMaster/External/LibTSMClass-2/LibTSMClass.lua"]:332: in function `_CheckIfDone'
[string "@TradeSkillMaster/LibTSM/Util/Delay.lua"]:123: in function <TradeSkillMaster/LibTSM/Util/Delay.lua:116>

Locals:

```

**Comment by ahakola** [comment]
Pushed out version 1.65 with hoping it to fix this issue.

**Comment by tgi-filip** [comment]
Solved, closing.
Thanks
