### ISSUE TITLE
[Bug report] Tint not showing for Use: Teaches you how to summon companion

### ISSUE THREAD

**Issue by dusekdan** [ahakola/AlreadyKnown#13]
Hi - great addon.

I am observing this behavior where tint gets correctly applied (in screenshot below it is grey tint) on Toys, Mounts and possibly everything else listed, **but is not correctly showing for items that have caption** `Use: Teaches you how to summon companion`.

I checked this with all addons but AlreadyKnown disabled, in Dalaran in the Toy shop and in the underbelly with the vendor that sells the "Skull" companion. Attaching screenshot below to illustrate - I do own `Blue Clockwork Rocket Bot` on this character, so it should also appear grey, but it doesn't.

![image](https://github.com/user-attachments/assets/b0ad0e57-6227-4e7d-835c-b8d336c253a4)

**Comment by ahakola** [comment]
When you have time, can you please go back and 
- hover your mouse over the `Blue Clockwork Rocket Bot` (or any other item that is not tinted correctly)
- while doing this, use ingame command `/alreadyknown itemtest`

This should open a popup with textfield. Copy the text from the textfield and paste it here (using codeblock gives better readability for the paste, but it isn't a requried).

**Comment by dusekdan** [comment]
```
ItemTest: AlreadyKnown 1.74 / 4.4.0
Item: [Blue Clockwork Rocket Bot] - Regions: 5/100 - Known: false
ItemLink: |cff0070dd|Hitem:54436::::::::85:::::::::|h[Blue Clockwork Rocket Bot]|h|r
3 FontString GameTooltipTextLeft1 Blue Clockwork Rocket Bot
5 FontString GameTooltipTextLeft2 Binds when picked up
7 FontString GameTooltipTextLeft3 Use: Teaches you how to summon this companion.
9 FontString GameTooltipTextLeft4 Vendor
10 FontString GameTooltipTextRight4 12  50  00 
```

**Comment by ahakola** [comment]
Version 1.75 should fix this issue. Don't hesitate to reopen this or open a new one if you run into something like this again!
