### ISSUE TITLE
Warlock Pet "Grimoire" Spellbooks not showing color change when learnt.

### ISSUE THREAD

**Issue by Shalaros** [ahakola/AlreadyKnown#14]
[https://1drv.ms/i/s!Agg0R0EOm1vcojX30Kh1jQNg1URi](url)

In the image linked above, I showcase the tooltip for the Imp's Firebolt spellbook. The tooltip confirms that I’ve already taught this spell to my Imp. However, the addon fails to change the book's color to indicate that the spell has been learned, which it should be doing.

**Comment by ahakola** [comment]
Can you hover your mouse over the item and use ingame command `/ak itemtest`

**Comment by Shalaros** [comment]
I disabled all my addons one by one and discovered that your addon works correctly on its own. However, it seems there's a conflict with another addon I use called "What's Training?". When I enable "What's Training?", your addon stops working, even though "What's Training?" continues to function without any issues while your addon is active.

Addon Description:
What's Training? is an addon for World of Warcraft Classic that adds a list of available trainer spells to the spell book, so you can easily know when to seek a class trainer out. Spells you already know are moved to the bottom. Mousing over a spell will show you its tooltip, with the cost to train attached to the bottom. Mousing over a category header will show you the total cost of training of spells in that section.

This is the info you requested:
ItemTest: AlreadyKnown 1.78 / 1.15.5
Item: [Grimoire of Firebolt (Rank 2)] (9 Recipe/0 Book) - Regions: 7/28 - Known: true
ItemLink: |cffffffff|Hitem:16302::::::::30:::::::::|h[Grimoire of Firebolt (Rank 2)]|h|r
3 FontString GameTooltipTextLeft1 Grimoire of Firebolt (Rank 2)
5 FontString GameTooltipTextLeft2 Binds when picked up
7 FontString GameTooltipTextLeft3 Unique
9 FontString GameTooltipTextLeft4 Classes: Warlock
11 FontString GameTooltipTextLeft5 Requires Level 8
13 FontString GameTooltipTextLeft6 Already known
15 FontString GameTooltipTextLeft7 Use: Teaches Imp Firebolt (Rank 2).

This is the info you requested but with the "What's Training?" addon enabled:
ItemTest: AlreadyKnown 1.78 / 1.15.5
Item: [Grimoire of Firebolt (Rank 2)] (9 Recipe/0 Book) - Regions: 11/34 - Known: true
ItemLink: |cffffffff|Hitem:16302::::::::30:::::::::|h[Grimoire of Firebolt (Rank 2)]|h|r
3 FontString GameTooltipTextLeft1 Grimoire of Firebolt (Rank 2)
5 FontString GameTooltipTextLeft2 Binds when picked up
7 FontString GameTooltipTextLeft3 Unique
9 FontString GameTooltipTextLeft4 Classes: Warlock
11 FontString GameTooltipTextLeft5 Requires Level 8
13 FontString GameTooltipTextLeft6 Already known
15 FontString GameTooltipTextLeft7 Use: Teaches Imp Firebolt (Rank 2).
29 FontString GameTooltipTextLeft9 ID 16302
30 FontString GameTooltipTextRight9 Bags: 0
31 FontString GameTooltipTextLeft10 Vendor
32 FontString GameTooltipTextRight10 25

**Comment by ahakola** [comment]
Based on the outputs you gave, in both cases this addon detects the Grimoires as known items, so next I took a quick look at the source code of the other addon you mentioned. I found out it is also changing the coloring of the vendor item icons (https://github.com/fusionpit/WhatsTraining/blob/master/WhatsTraining.lua#L494-L497), so it is a race to the last place who gets the final say on the color for the icons.
