### ISSUE TITLE
known recipes not colored green

### ISSUE THREAD

**Issue by Netspider** [ahakola/AlreadyKnown#3]
Hello,

I'm currently at Emrul Riknussun (cooking ingredients in IF) with a german client and both recipes are not tinted green although I (lvl 60 hunter) known them, the text says "Bereits bekannt". addon 1.34-bcc.
These are the first recipes I see since the update so I don't know if some are maybe colored.
[Edit: Same for leatherworking recipes from Miranda Breechlock/argent dawn]

**Comment by ahakola** [comment]
Are you talking about recipies at vendor or in you backbag? Currently addon only supports tinting in MerchantFrame, AuctionHouseUI and GuildBankUI. If the item is in any of the previously listed frames, please type `/ak debug`, browse to the item and take a copypaste and/or screenshot of the chat output (you can turn off the debugging with commanding `/ak debug` again).

**Comment by Netspider** [comment]
creepy, today it is working! The only addon with an update was DBM...

**Comment by Netspider** [comment]
it happened again:
![WoWScrnShot_060121_181940](https://user-images.githubusercontent.com/347282/120357743-0f5e7200-c306-11eb-9fef-16676ff35586.jpg)

**Comment by ahakola** [comment]
Published new version 1.35 that should fix this. Let me know if this doesn't fix the problem and I'll ask you for more information since I haven't been able to reproduce this error with my newbie characters.

**Comment by Netspider** [comment]
Have had no problems since 1.35, thanks.
