### ISSUE TITLE
Request for Support for Non-Combat Pets in Classic

### ISSUE THREAD

**Issue by Gogo1951** [ahakola/AlreadyKnown#7]

**Comment by Gogo1951** [comment]
Here's a screenshot from Wrath Classic for reference.

![image](https://user-images.githubusercontent.com/55365231/212109128-ad552a16-0cb6-4411-8d34-10272db92e1a.png)

**Comment by Gogo1951** [comment]
Here's a mount vendor window.

![image](https://user-images.githubusercontent.com/55365231/212110711-1b875e5b-6506-4e48-a004-51f1c3a48186.png)

**Comment by ahakola** [comment]
Seems like Wrath either returns pet collection data differently or uses different functions for it from Retail. I'll look into the pet situation when I have time to work on addons.

If it isn't too much asked, could you go back to the pet vendor and hover your mouse over one of the pets you already own in the vendor frame and use command `/ak itemtest` or `/alreadyknown itemtest` and paste the results here for reference data.

**Comment by Gogo1951** [comment]
![image](https://user-images.githubusercontent.com/55365231/212219083-0d5ab0e0-1f11-46a0-93d2-29ab239dfeee.png)

ItemTest: [Black Kingsnake] - Regions: 18/76 - Known: false
ItemLink: |cffffffff|Hitem:10360::::::::80:::::::::|h[Black Kingsnake]|h|r
3 FontString GameTooltipTextLeft1 Black Kingsnake
5 FontString GameTooltipTextLeft2 Use: Teaches you how to summon this companion.
9 FontString GameTooltipTextLeft4 TSM General Info
11 FontString GameTooltipTextLeft5   Vendor Buy Price
12 FontString GameTooltipTextRight5 42s 50c
13 FontString GameTooltipTextLeft6   Vendor Sell Price
14 FontString GameTooltipTextRight6 12s 50c
15 FontString GameTooltipTextLeft7 TSM AuctionDB
16 FontString GameTooltipTextRight7 5 auctions (10 Hr 40 Min ago)
17 FontString GameTooltipTextLeft8   Min Buyout
18 FontString GameTooltipTextRight8 2g 84s 90c
29 FontString GameTooltipTextLeft9   Market Value
30 FontString GameTooltipTextRight9 [35%] 4g 36s 12c
31 FontString GameTooltipTextLeft10   Region Market Value Avg
32 FontString GameTooltipTextRight10 16g 82s 08c
33 FontString GameTooltipTextLeft11 ATT > Zone > Orgrimmar
34 FontString GameTooltipTextRight11 Vendor > Xan'tish
37 FontString GameTooltipTextLeft13 ID 10360

**Comment by ahakola** [comment]
Pushed out version 1.53 with some kind of bandaid fix for this, but beware since I strongly assume there will be some false positives/negatives with it. As far as I know, there isn't any real API to check if the companion pet is already known or if the vendor item has any relation to any companion pets you already own.

**Comment by ahakola** [comment]
The current method compares the icons and sees if there is at least a partial match between the item name and the companion pet name so it should work for most of the companions, but might miss some of them.

**Comment by ahakola** [comment]
And btw. if you are interested in finding out the pet names from your collection you can use this kind of approach:
```
for i = 1, GetNumCompanions("CRITTER") do
	local creatureId, creatureName, creatureSpellId, icon, issummoned, mountType = GetCompanionInfo("CRITTER", i)
end
```
but without making some kind of translation table between vendor sold itemId and collection creatureId there isn't 100% sure way to match these.

**Comment by ahakola** [comment]
Closing this as PetJournal was already added to Wratch Classic in patch 3.4.3 (commit c7e0ddb), but forgot to close this issue back then.
