### ISSUE TITLE
[Retail] Toy from WotlK timewalking vendor doesn't get colored red

### ISSUE THREAD

**Issue by Nifelhein** [ahakola/AlreadyKnown#9]
![image](https://user-images.githubusercontent.com/29641025/224059007-ce7a50c2-f502-4f4d-a66d-14962e55d24e.png)
![image](https://user-images.githubusercontent.com/29641025/224059152-aaabb297-61b7-4924-8c80-fb2f683d582c.png)

**Comment by ahakola** [comment]
Can you hover your mouse over the item and use ingame command `/ak itemtest` and paste the results here?

If you want to format it properly, either select all the pasted text after pasting and press *CTRL+E* or copy the code tags from below and paste your text in between:
\```
Paste the results here
\```

and the results should look like this:
```
Paste the results here
```

**Comment by Nifelhein** [comment]
Sorry it took me so long to get back to this. I followed your directions on the popup window when I typed the /ak itemtest command and found out that I had another addon coloring the known items that was superseding Already Known.

Culprit was S&L merchant frame module, turning it off makes alreadyknown works as intended. I am very sorry for wasting your time
